In [1]:
# Import dependencies
import pandas as pd
import numpy as np
from pathlib import Path
pd.set_option('max_colwidth', 400)

### Extract the olympic_hosts.csv Data.

In [2]:
# Store filepaths into variables 
olympic_hosts_to_load = Path("olympic_hosts.csv")

# Read Olympic Hosts Data File and store into a Pandas DataFrame
host_data = pd.read_csv(olympic_hosts_to_load)
host_data.head()

,game_slug,game_end_date,game_start_date,game_location,game_name,game_season,game_year
0,beijing-2022,2022-02-20T12:00:00Z,2022-02-04T15:00:00Z,China,Beijing 2022,Winter,2022
1,tokyo-2020,2021-08-08T14:00:00Z,2021-07-23T11:00:00Z,Japan,Tokyo 2020,Summer,2020
2,pyeongchang-2018,2018-02-25T08:00:00Z,2018-02-08T23:00:00Z,Republic of Korea,PyeongChang 2018,Winter,2018
3,rio-2016,2016-08-21T21:00:00Z,2016-08-05T12:00:00Z,Brazil,Rio 2016,Summer,2016
4,sochi-2014,2014-02-23T16:00:00Z,2014-02-07T04:00:00Z,Russian Federation,Sochi 2014,Winter,2014

In [3]:
# Convert the datetime columns to datetime format and remove the time 
host_data['game_end_date'] = pd.to_datetime(host_data['game_end_date'], format='%Y-%m-%dT%H:%M:%SZ').dt.date
host_data['game_start_date'] = pd.to_datetime(host_data['game_start_date'], format='%Y-%m-%dT%H:%M:%SZ').dt.date

# Display the first few rows of the DataFrame
host_data.head()

,game_slug,game_end_date,game_start_date,game_location,game_name,game_season,game_year
0,beijing-2022,2022-02-20,2022-02-04,China,Beijing 2022,Winter,2022
1,tokyo-2020,2021-08-08,2021-07-23,Japan,Tokyo 2020,Summer,2020
2,pyeongchang-2018,2018-02-25,2018-02-08,Republic of Korea,PyeongChang 2018,Winter,2018
3,rio-2016,2016-08-21,2016-08-05,Brazil,Rio 2016,Summer,2016
4,sochi-2014,2014-02-23,2014-02-07,Russian Federation,Sochi 2014,Winter,2014

In [4]:
# Create new columns for city and year
host_data[['city', 'year']] = host_data['game_name'].str.split(' ', n=1, expand=True)

# Merge back the remaining parts of the city name
host_data['city'] = host_data.apply(lambda x: ' '.join([x['city'], x['year']]), axis=1)

# Drop the 'year' column
host_data.drop('year', axis=1, inplace=True)

# Display the modified DataFrame
host_data.head(20)

,game_slug,game_end_date,game_start_date,game_location,game_name,game_season,game_year,city
0,beijing-2022,2022-02-20,2022-02-04,China,Beijing 2022,Winter,2022,Beijing 2022
1,tokyo-2020,2021-08-08,2021-07-23,Japan,Tokyo 2020,Summer,2020,Tokyo 2020
2,pyeongchang-2018,2018-02-25,2018-02-08,Republic of Korea,PyeongChang 2018,Winter,2018,PyeongChang 2018
3,rio-2016,2016-08-21,2016-08-05,Brazil,Rio 2016,Summer,2016,Rio 2016
4,sochi-2014,2014-02-23,2014-02-07,Russian Federation,Sochi 2014,Winter,2014,Sochi 2014
5,london-2012,2012-08-12,2012-07-27,Great Britain,London 2012,Summer,2012,London 2012
6,vancouver-2010,2010-02-28,2010-02-12,Canada,Vancouver 2010,Winter,2010,Vancouver 2010
7,beijing-2008,2008-08-24,2008-08-08,China,Beijing 2008,Summer,2008,Beijing 2008
8,turin-2006,2006-02-26,2006-02-10,Italy,Turin 2006,Winter,2006,Turin 2006
9,athens-2004,2004-08-29,2004-08-13,Greece,Athens 2004,Summer,2004,Athens 2004
10,salt-lake-city-2002,2002-02-24,2002-02-08,United States,Salt Lake City 2002,Winter,2002,Salt Lake City 2002
11,sydney-2000,2000-10-01,2000-09-15,Australia,Sydney 2000,Summer,2000,Sydney 2000
12,nagano-1998,1998-02-22,1998-02-06,Japan,Nagano 1998,Winter,1998,Nagano 1998
13,atlanta-1996,1996-08-05,1996-07-19,United States,Atlanta 1996,Summer,1996,Atlanta 1996
14,lillehammer-1994,1994-02-27,1994-02-12,Norway,Lillehammer 1994,Winter,1994,Lillehammer 1994
15,barcelona-1992,1992-08-09,1992-07-25,Spain,Barcelona 1992,Summer,1992,Barcelona 1992
16,albertville-1992,1992-02-23,1992-02-08,France,Albertville 1992,Winter,1992,Albertville 1992
17,seoul-1988,1988-10-02,1988-09-16,Republic of Korea,Seoul 1988,Summer,1988,Seoul 1988
18,calgary-1988,1988-02-28,1988-02-13,Canada,Calgary 1988,Winter,1988,Calgary 1988
19,los-angeles-1984,1984-08-12,1984-07-28,United States,Los Angeles 1984,Summer,1984,Los Angeles 1984

In [5]:
# Split the city and year in the 'city' column
host_data[['city', 'year']] = host_data['game_name'].str.rsplit(' ', n=1, expand=True)

# Display the modified DataFrame
host_data.head(20)

,game_slug,game_end_date,game_start_date,game_location,game_name,game_season,game_year,city,year
0,beijing-2022,2022-02-20,2022-02-04,China,Beijing 2022,Winter,2022,Beijing,2022
1,tokyo-2020,2021-08-08,2021-07-23,Japan,Tokyo 2020,Summer,2020,Tokyo,2020
2,pyeongchang-2018,2018-02-25,2018-02-08,Republic of Korea,PyeongChang 2018,Winter,2018,PyeongChang,2018
3,rio-2016,2016-08-21,2016-08-05,Brazil,Rio 2016,Summer,2016,Rio,2016
4,sochi-2014,2014-02-23,2014-02-07,Russian Federation,Sochi 2014,Winter,2014,Sochi,2014
5,london-2012,2012-08-12,2012-07-27,Great Britain,London 2012,Summer,2012,London,2012
6,vancouver-2010,2010-02-28,2010-02-12,Canada,Vancouver 2010,Winter,2010,Vancouver,2010
7,beijing-2008,2008-08-24,2008-08-08,China,Beijing 2008,Summer,2008,Beijing,2008
8,turin-2006,2006-02-26,2006-02-10,Italy,Turin 2006,Winter,2006,Turin,2006
9,athens-2004,2004-08-29,2004-08-13,Greece,Athens 2004,Summer,2004,Athens,2004
10,salt-lake-city-2002,2002-02-24,2002-02-08,United States,Salt Lake City 2002,Winter,2002,Salt Lake City,2002
11,sydney-2000,2000-10-01,2000-09-15,Australia,Sydney 2000,Summer,2000,Sydney,2000
12,nagano-1998,1998-02-22,1998-02-06,Japan,Nagano 1998,Winter,1998,Nagano,1998
13,atlanta-1996,1996-08-05,1996-07-19,United States,Atlanta 1996,Summer,1996,Atlanta,1996
14,lillehammer-1994,1994-02-27,1994-02-12,Norway,Lillehammer 1994,Winter,1994,Lillehammer,1994
15,barcelona-1992,1992-08-09,1992-07-25,Spain,Barcelona 1992,Summer,1992,Barcelona,1992
16,albertville-1992,1992-02-23,1992-02-08,France,Albertville 1992,Winter,1992,Albertville,1992
17,seoul-1988,1988-10-02,1988-09-16,Republic of Korea,Seoul 1988,Summer,1988,Seoul,1988
18,calgary-1988,1988-02-28,1988-02-13,Canada,Calgary 1988,Winter,1988,Calgary,1988
19,los-angeles-1984,1984-08-12,1984-07-28,United States,Los Angeles 1984,Summer,1984,Los Angeles,1984

In [6]:
# Drop unwanted columns
host_data.drop(['game_name', 'year'], axis=1, inplace=True)

# Display the first few rows
host_data.head(30)

,game_slug,game_end_date,game_start_date,game_location,game_season,game_year,city
0,beijing-2022,2022-02-20,2022-02-04,China,Winter,2022,Beijing
1,tokyo-2020,2021-08-08,2021-07-23,Japan,Summer,2020,Tokyo
2,pyeongchang-2018,2018-02-25,2018-02-08,Republic of Korea,Winter,2018,PyeongChang
3,rio-2016,2016-08-21,2016-08-05,Brazil,Summer,2016,Rio
4,sochi-2014,2014-02-23,2014-02-07,Russian Federation,Winter,2014,Sochi
5,london-2012,2012-08-12,2012-07-27,Great Britain,Summer,2012,London
6,vancouver-2010,2010-02-28,2010-02-12,Canada,Winter,2010,Vancouver
7,beijing-2008,2008-08-24,2008-08-08,China,Summer,2008,Beijing
8,turin-2006,2006-02-26,2006-02-10,Italy,Winter,2006,Turin
9,athens-2004,2004-08-29,2004-08-13,Greece,Summer,2004,Athens
10,salt-lake-city-2002,2002-02-24,2002-02-08,United States,Winter,2002,Salt Lake City
11,sydney-2000,2000-10-01,2000-09-15,Australia,Summer,2000,Sydney
12,nagano-1998,1998-02-22,1998-02-06,Japan,Winter,1998,Nagano
13,atlanta-1996,1996-08-05,1996-07-19,United States,Summer,1996,Atlanta
14,lillehammer-1994,1994-02-27,1994-02-12,Norway,Winter,1994,Lillehammer
15,barcelona-1992,1992-08-09,1992-07-25,Spain,Summer,1992,Barcelona
16,albertville-1992,1992-02-23,1992-02-08,France,Winter,1992,Albertville
17,seoul-1988,1988-10-02,1988-09-16,Republic of Korea,Summer,1988,Seoul
18,calgary-1988,1988-02-28,1988-02-13,Canada,Winter,1988,Calgary
19,los-angeles-1984,1984-08-12,1984-07-28,United States,Summer,1984,Los Angeles
20,sarajevo-1984,1984-02-19,1984-02-08,Yugoslavia,Winter,1984,Sarajevo
21,moscow-1980,1980-08-03,1980-07-19,USSR,Summer,1980,Moscow
22,lake-placid-1980,1980-02-24,1980-02-13,United States,Winter,1980,Lake Placid
23,montreal-1976,1976-07-31,1976-07-17,Canada,Summer,1976,Montreal
24,innsbruck-1976,1976-02-15,1976-02-04,Austria,Winter,1976,Innsbruck
25,munich-1972,1972-09-11,1972-08-26,Federal Republic of Germany,Summer,1972,Munich
26,sapporo-1972,1972-02-13,1972-02-02,Japan,Winter,1972,Sapporo
27,mexico-city-1968,1968-10-28,1968-10-12,Mexico,Summer,1968,Mexico City
28,grenoble-1968,1968-02-18,1968-02-06,France,Winter,1968,Grenoble
29,tokyo-1964,1964-10-24,1964-10-09,Japan,Summer,1964,Tokyo

In [7]:
# Rename columns
host_data.rename(columns={'game_end_date': 'end_date', 
                          'game_start_date': 'start_date', 
                          'game_location': 'country',
                          'game_season': 'season'}, inplace=True)

# Display the first few rows
host_data.head(20)

,game_slug,end_date,start_date,country,season,game_year,city
0,beijing-2022,2022-02-20,2022-02-04,China,Winter,2022,Beijing
1,tokyo-2020,2021-08-08,2021-07-23,Japan,Summer,2020,Tokyo
2,pyeongchang-2018,2018-02-25,2018-02-08,Republic of Korea,Winter,2018,PyeongChang
3,rio-2016,2016-08-21,2016-08-05,Brazil,Summer,2016,Rio
4,sochi-2014,2014-02-23,2014-02-07,Russian Federation,Winter,2014,Sochi
5,london-2012,2012-08-12,2012-07-27,Great Britain,Summer,2012,London
6,vancouver-2010,2010-02-28,2010-02-12,Canada,Winter,2010,Vancouver
7,beijing-2008,2008-08-24,2008-08-08,China,Summer,2008,Beijing
8,turin-2006,2006-02-26,2006-02-10,Italy,Winter,2006,Turin
9,athens-2004,2004-08-29,2004-08-13,Greece,Summer,2004,Athens
10,salt-lake-city-2002,2002-02-24,2002-02-08,United States,Winter,2002,Salt Lake City
11,sydney-2000,2000-10-01,2000-09-15,Australia,Summer,2000,Sydney
12,nagano-1998,1998-02-22,1998-02-06,Japan,Winter,1998,Nagano
13,atlanta-1996,1996-08-05,1996-07-19,United States,Summer,1996,Atlanta
14,lillehammer-1994,1994-02-27,1994-02-12,Norway,Winter,1994,Lillehammer
15,barcelona-1992,1992-08-09,1992-07-25,Spain,Summer,1992,Barcelona
16,albertville-1992,1992-02-23,1992-02-08,France,Winter,1992,Albertville
17,seoul-1988,1988-10-02,1988-09-16,Republic of Korea,Summer,1988,Seoul
18,calgary-1988,1988-02-28,1988-02-13,Canada,Winter,1988,Calgary
19,los-angeles-1984,1984-08-12,1984-07-28,United States,Summer,1984,Los Angeles

In [8]:
# Reorder columns
host_cleaned = host_data[['game_slug', 'start_date', 'end_date', 'season', 'country', 'city', 'game_year']]

host_cleaned.head()

,game_slug,start_date,end_date,season,country,city,game_year
0,beijing-2022,2022-02-04,2022-02-20,Winter,China,Beijing,2022
1,tokyo-2020,2021-07-23,2021-08-08,Summer,Japan,Tokyo,2020
2,pyeongchang-2018,2018-02-08,2018-02-25,Winter,Republic of Korea,PyeongChang,2018
3,rio-2016,2016-08-05,2016-08-21,Summer,Brazil,Rio,2016
4,sochi-2014,2014-02-07,2014-02-23,Winter,Russian Federation,Sochi,2014

In [9]:
# Export the DataFrame as a CSV file. 
host_cleaned.to_csv("cleaned_olympic_hosts.csv", index=False)