In [1]:
# Import dependencies
import pandas as pd
import numpy as np
from pathlib import Path
pd.set_option('max_colwidth', 400)

In [2]:
Olympic_games_olympic_results_data = Path("Olympic_Files/olympic_results.csv")

# Read medals and results Data File and store into Pandas DataFrames
results_data = pd.read_csv(Olympic_games_olympic_results_data)
results_data.head()

,discipline_title,event_title,slug_game,participant_type,medal_type,athletes,rank_equal,rank_position,country_name,country_code,country_3_letter_code,athlete_url,athlete_full_name,value_unit,value_type
0,Curling,Mixed Doubles,beijing-2022,GameTeam,GOLD,"[('Stefania CONSTANTINI', 'https://olympics.com/en/athletes/stefania-constantini'), ('Amos MOSANER', 'https://olympics.com/en/athletes/amos-mosaner')]",False,1,Italy,IT,ITA,NaN,NaN,NaN,NaN
1,Curling,Mixed Doubles,beijing-2022,GameTeam,SILVER,"[('Kristin SKASLIEN', 'https://olympics.com/en/athletes/kristin-skaslien'), ('Magnus NEDREGOTTEN', 'https://olympics.com/en/athletes/magnus-nedregotten')]",False,2,Norway,NO,NOR,NaN,NaN,NaN,NaN
2,Curling,Mixed Doubles,beijing-2022,GameTeam,BRONZE,"[('Almida DE VAL', 'https://olympics.com/en/athletes/almida-de-val'), ('Oskar ERIKSSON', 'https://olympics.com/en/athletes/oskar-eriksson')]",False,3,Sweden,SE,SWE,NaN,NaN,NaN,NaN
3,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,"[('Jennifer DODDS', 'https://olympics.com/en/athletes/jennifer-dodds'), ('Bruce MOUAT', 'https://olympics.com/en/athletes/bruce-mouat')]",False,4,Great Britain,GB,GBR,NaN,NaN,NaN,NaN
4,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,"[('Rachel HOMAN', 'https://olympics.com/en/athletes/rachel-homan'), ('John MORRIS', 'https://olympics.com/en/athletes/john-morris')]",False,5,Canada,CA,CAN,NaN,NaN,NaN,NaN

In [3]:
results_data.columns

Index(['discipline_title', 'event_title', 'slug_game', 'participant_type',
       'medal_type', 'athletes', 'rank_equal', 'rank_position', 'country_name',
       'country_code', 'country_3_letter_code', 'athlete_url',
       'athlete_full_name', 'value_unit', 'value_type'],
      dtype='object')

In [4]:
# Count NaN values in the 'athlete_full_name' column
nan_count = results_data['athlete_full_name'].isna().sum()

print("Number of NaN values in 'athlete_full_name' column:", nan_count)

Number of NaN values in 'athlete_full_name' column: 21158

In [5]:
# Replace missing values with an empty string
results_data['athlete_full_name'] = results_data['athlete_full_name'].fillna('')

# Splitting last name into components
results_data[['first_name', 'last_name']] = results_data["athlete_full_name"].apply(lambda x: pd.Series(str(x).split(' ', 1)))

# Capitalizing each component of the last name
results_data['last_name'] = results_data['last_name'].apply(lambda x: ' '.join([part.capitalize() for part in str(x).split()]))

# Capitalizing first name
results_data['first_name'] = results_data['first_name'].str.capitalize()

results_data.head()

,discipline_title,event_title,slug_game,participant_type,medal_type,athletes,rank_equal,rank_position,country_name,country_code,country_3_letter_code,athlete_url,athlete_full_name,value_unit,value_type,first_name,last_name
0,Curling,Mixed Doubles,beijing-2022,GameTeam,GOLD,"[('Stefania CONSTANTINI', 'https://olympics.com/en/athletes/stefania-constantini'), ('Amos MOSANER', 'https://olympics.com/en/athletes/amos-mosaner')]",False,1,Italy,IT,ITA,NaN,,NaN,NaN,,Nan
1,Curling,Mixed Doubles,beijing-2022,GameTeam,SILVER,"[('Kristin SKASLIEN', 'https://olympics.com/en/athletes/kristin-skaslien'), ('Magnus NEDREGOTTEN', 'https://olympics.com/en/athletes/magnus-nedregotten')]",False,2,Norway,NO,NOR,NaN,,NaN,NaN,,Nan
2,Curling,Mixed Doubles,beijing-2022,GameTeam,BRONZE,"[('Almida DE VAL', 'https://olympics.com/en/athletes/almida-de-val'), ('Oskar ERIKSSON', 'https://olympics.com/en/athletes/oskar-eriksson')]",False,3,Sweden,SE,SWE,NaN,,NaN,NaN,,Nan
3,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,"[('Jennifer DODDS', 'https://olympics.com/en/athletes/jennifer-dodds'), ('Bruce MOUAT', 'https://olympics.com/en/athletes/bruce-mouat')]",False,4,Great Britain,GB,GBR,NaN,,NaN,NaN,,Nan
4,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,"[('Rachel HOMAN', 'https://olympics.com/en/athletes/rachel-homan'), ('John MORRIS', 'https://olympics.com/en/athletes/john-morris')]",False,5,Canada,CA,CAN,NaN,,NaN,NaN,,Nan

In [6]:
def split_and_capitalize_last_name(full_name):
    if isinstance(full_name, str):
        # Splitting the full name into parts
        name_parts = full_name.split(' ')
        # Captializing the last name parts
        if len(name_parts) > 1:
            last_name_parts = []
            for part in name_parts[1:]:
                if '-' in part:
                    hyphen_parts = part.split('-')
                    capitalized_parts = [p.capitalize() for p in hyphen_parts]
                    last_name_parts.extend(capitalized_parts)
                else:
                    last_name_parts.append(part.capitalize())
            return ' '.join(last_name_parts)

# Test the function with a sample value
print(split_and_capitalize_last_name("Cooper Woods-topalovic"))
print(split_and_capitalize_last_name("Almida De val"))

Woods Topalovic
De Val

In [7]:
def split_and_capitalize_last_name(full_name):
    if isinstance(full_name, str):
        # Splitting the full name into parts
        name_parts = full_name.split(' ')
        # Captializing the last name parts
        if len(name_parts) > 1:
            last_name_parts = []
            for part in name_parts[1:]:
                if '-' in part:
                    hyphen_parts = part.split('-')
                    capitalized_parts = [p.capitalize() for p in hyphen_parts]
                    last_name_parts.extend(capitalized_parts)
                else:
                    last_name_parts.append(part.capitalize())
            return ' '.join(last_name_parts)

# Test the function with a sample value
print(split_and_capitalize_last_name("Cooper Woods-topalovic"))
print(split_and_capitalize_last_name("Almida De val"))

results_data.head()

Woods Topalovic
De Val

,discipline_title,event_title,slug_game,participant_type,medal_type,athletes,rank_equal,rank_position,country_name,country_code,country_3_letter_code,athlete_url,athlete_full_name,value_unit,value_type,first_name,last_name
0,Curling,Mixed Doubles,beijing-2022,GameTeam,GOLD,"[('Stefania CONSTANTINI', 'https://olympics.com/en/athletes/stefania-constantini'), ('Amos MOSANER', 'https://olympics.com/en/athletes/amos-mosaner')]",False,1,Italy,IT,ITA,NaN,,NaN,NaN,,Nan
1,Curling,Mixed Doubles,beijing-2022,GameTeam,SILVER,"[('Kristin SKASLIEN', 'https://olympics.com/en/athletes/kristin-skaslien'), ('Magnus NEDREGOTTEN', 'https://olympics.com/en/athletes/magnus-nedregotten')]",False,2,Norway,NO,NOR,NaN,,NaN,NaN,,Nan
2,Curling,Mixed Doubles,beijing-2022,GameTeam,BRONZE,"[('Almida DE VAL', 'https://olympics.com/en/athletes/almida-de-val'), ('Oskar ERIKSSON', 'https://olympics.com/en/athletes/oskar-eriksson')]",False,3,Sweden,SE,SWE,NaN,,NaN,NaN,,Nan
3,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,"[('Jennifer DODDS', 'https://olympics.com/en/athletes/jennifer-dodds'), ('Bruce MOUAT', 'https://olympics.com/en/athletes/bruce-mouat')]",False,4,Great Britain,GB,GBR,NaN,,NaN,NaN,,Nan
4,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,"[('Rachel HOMAN', 'https://olympics.com/en/athletes/rachel-homan'), ('John MORRIS', 'https://olympics.com/en/athletes/john-morris')]",False,5,Canada,CA,CAN,NaN,,NaN,NaN,,Nan

In [8]:
results_data.drop('country_code', axis=1, inplace=True)
results_data.head()

,discipline_title,event_title,slug_game,participant_type,medal_type,athletes,rank_equal,rank_position,country_name,country_3_letter_code,athlete_url,athlete_full_name,value_unit,value_type,first_name,last_name
0,Curling,Mixed Doubles,beijing-2022,GameTeam,GOLD,"[('Stefania CONSTANTINI', 'https://olympics.com/en/athletes/stefania-constantini'), ('Amos MOSANER', 'https://olympics.com/en/athletes/amos-mosaner')]",False,1,Italy,ITA,NaN,,NaN,NaN,,Nan
1,Curling,Mixed Doubles,beijing-2022,GameTeam,SILVER,"[('Kristin SKASLIEN', 'https://olympics.com/en/athletes/kristin-skaslien'), ('Magnus NEDREGOTTEN', 'https://olympics.com/en/athletes/magnus-nedregotten')]",False,2,Norway,NOR,NaN,,NaN,NaN,,Nan
2,Curling,Mixed Doubles,beijing-2022,GameTeam,BRONZE,"[('Almida DE VAL', 'https://olympics.com/en/athletes/almida-de-val'), ('Oskar ERIKSSON', 'https://olympics.com/en/athletes/oskar-eriksson')]",False,3,Sweden,SWE,NaN,,NaN,NaN,,Nan
3,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,"[('Jennifer DODDS', 'https://olympics.com/en/athletes/jennifer-dodds'), ('Bruce MOUAT', 'https://olympics.com/en/athletes/bruce-mouat')]",False,4,Great Britain,GBR,NaN,,NaN,NaN,,Nan
4,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,"[('Rachel HOMAN', 'https://olympics.com/en/athletes/rachel-homan'), ('John MORRIS', 'https://olympics.com/en/athletes/john-morris')]",False,5,Canada,CAN,NaN,,NaN,NaN,,Nan

In [9]:
# Fill missing values with empty string
results_data['athletes'].fillna('', inplace=True)

# Initialize lists to store extracted data
athlete_data = []

# Iterate over each row in the DataFrame
for idx, entry in enumerate(results_data['athletes']):
    # Split the string by '), (' to separate each athlete's information
    athlete_info = entry.strip('[]').split("), ('")
    # Extract athlete names and URLs from each entry
    for info in athlete_info:
        # Split each entry by ', ' to separate athlete name and URL
        name_url = info.split("', '")
        # Check if name_url has at least two elements
        if len(name_url) >= 2:
            # Extract athlete name and URL
            athlete_name = name_url[0].strip("('")
            athlete_url = name_url[1].strip("')")
            # Append the extracted data to the list
            athlete_data.append({'First Name': athlete_name.split()[0],
                                  'Last Name': split_and_capitalize_last_name(athlete_name),
                                  'URL': athlete_url,
                                  'participant_type': results_data.iloc[idx]['participant_type']})

# Create a DataFrame from the extracted data
df = pd.DataFrame(athlete_data)

df.head()

,First Name,Last Name,URL,participant_type
0,Stefania,Constantini,https://olympics.com/en/athletes/stefania-constantini,GameTeam
1,Amos,Mosaner,https://olympics.com/en/athletes/amos-mosaner,GameTeam
2,Kristin,Skaslien,https://olympics.com/en/athletes/kristin-skaslien,GameTeam
3,Magnus,Nedregotten,https://olympics.com/en/athletes/magnus-nedregotten,GameTeam
4,Almida,De Val,https://olympics.com/en/athletes/almida-de-val,GameTeam

In [10]:
import re

# Assuming results_data is a Pandas DataFrame
athlete_data_list = []

# Iterate over each string representation of list of tuples
for athlete_list_str in results_data['athletes']:
    # Handle empty strings
    if not athlete_list_str.strip():
        continue
    
    # Split the string into tuples
    athlete_list = athlete_list_str.split("), (")
    
    # Remove leading and trailing brackets for the first and last tuples
    if len(athlete_list) > 0:
        athlete_list[0] = athlete_list[0].lstrip("[(")
    if len(athlete_list) > 1:
        athlete_list[-1] = athlete_list[-1].rstrip(")]")
    
    # Iterate over each tuple in the list
    for athlete_data_str in athlete_list:
        # Try to match patterns where name and URL are separated by different delimiters
        match = re.match(r"['\"]([^'\"]*)['\"](?:, (['\"][^'\"]*['\"]))?", athlete_data_str)
        if match:
            athlete_name = match.group(1)
            athlete_url = match.group(2)
            
            # Split the name into first and last name
            name_parts = athlete_name.split(' ')
            if len(name_parts) >= 2:
                first_name = name_parts[0]
                last_name = ' '.join(name_parts[1:])
            else:
                # If name doesn't have both first and last name, use full name as first name
                first_name = athlete_name
                last_name = ""
            
            # If URL is missing, set it to None
            if athlete_url:
                athlete_url = athlete_url.strip('"')
            else:
                athlete_url = None
            
            athlete_data_list.append({
                'First Name': first_name,
                'Last Name': last_name,
                'URL': athlete_url
            })
        else:
            print(f"Failed to extract name and URL from: {athlete_data_str}")

# Convert the list of dictionaries into a DataFrame
athlete_df = pd.DataFrame(athlete_data_list)


athlete_df.head()

,First Name,Last Name,URL
0,Stefania,CONSTANTINI,'https://olympics.com/en/athletes/stefania-constantini'
1,Amos,MOSANER,'https://olympics.com/en/athletes/amos-mosaner'
2,Kristin,SKASLIEN,'https://olympics.com/en/athletes/kristin-skaslien'
3,Magnus,NEDREGOTTEN,'https://olympics.com/en/athletes/magnus-nedregotten'
4,Almida,DE VAL,'https://olympics.com/en/athletes/almida-de-val'

In [11]:
import ast

# Function to extract athlete information
def separate_athletes(row):
    try:
        athletes_info = row['athletes']
        if athletes_info:
            athlete_info = ast.literal_eval(athletes_info)
            if isinstance(athlete_info, list) and len(athlete_info) >= 2:
                athlete1 = athlete_info[0]
                athlete2 = athlete_info[1]
                athlete1_first_name, athlete1_last_name = athlete1[0].split(maxsplit=1)
                athlete2_first_name, athlete2_last_name = athlete2[0].split(maxsplit=1)
                return pd.Series([
                    athlete1_first_name, athlete1_last_name, athlete1[1], 
                    athlete2_first_name, athlete2_last_name, athlete2[1]
                ])
            else:
                return pd.Series([None, None, None, None, None, None])
        else:
            return pd.Series([None, None, None, None, None, None])
    except Exception as e:
        print(f"Error processing row: {row}")
        print(f"Error message: {e}")
        return pd.Series([None, None, None, None, None, None])

# Apply the function to each row
results_data[['athlete1_first_name', 'athlete1_last_name', 'athlete1_url', 
              'athlete2_first_name', 'athlete2_last_name', 'athlete2_url']] = results_data.apply(separate_athletes, axis=1)



results_data.head()

,discipline_title,event_title,slug_game,participant_type,medal_type,athletes,rank_equal,rank_position,country_name,country_3_letter_code,...,value_unit,value_type,first_name,last_name,athlete1_first_name,athlete1_last_name,athlete1_url,athlete2_first_name,athlete2_last_name,athlete2_url
0,Curling,Mixed Doubles,beijing-2022,GameTeam,GOLD,"[('Stefania CONSTANTINI', 'https://olympics.com/en/athletes/stefania-constantini'), ('Amos MOSANER', 'https://olympics.com/en/athletes/amos-mosaner')]",False,1,Italy,ITA,...,NaN,NaN,,Nan,Stefania,CONSTANTINI,https://olympics.com/en/athletes/stefania-constantini,Amos,MOSANER,https://olympics.com/en/athletes/amos-mosaner
1,Curling,Mixed Doubles,beijing-2022,GameTeam,SILVER,"[('Kristin SKASLIEN', 'https://olympics.com/en/athletes/kristin-skaslien'), ('Magnus NEDREGOTTEN', 'https://olympics.com/en/athletes/magnus-nedregotten')]",False,2,Norway,NOR,...,NaN,NaN,,Nan,Kristin,SKASLIEN,https://olympics.com/en/athletes/kristin-skaslien,Magnus,NEDREGOTTEN,https://olympics.com/en/athletes/magnus-nedregotten
2,Curling,Mixed Doubles,beijing-2022,GameTeam,BRONZE,"[('Almida DE VAL', 'https://olympics.com/en/athletes/almida-de-val'), ('Oskar ERIKSSON', 'https://olympics.com/en/athletes/oskar-eriksson')]",False,3,Sweden,SWE,...,NaN,NaN,,Nan,Almida,DE VAL,https://olympics.com/en/athletes/almida-de-val,Oskar,ERIKSSON,https://olympics.com/en/athletes/oskar-eriksson
3,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,"[('Jennifer DODDS', 'https://olympics.com/en/athletes/jennifer-dodds'), ('Bruce MOUAT', 'https://olympics.com/en/athletes/bruce-mouat')]",False,4,Great Britain,GBR,...,NaN,NaN,,Nan,Jennifer,DODDS,https://olympics.com/en/athletes/jennifer-dodds,Bruce,MOUAT,https://olympics.com/en/athletes/bruce-mouat
4,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,"[('Rachel HOMAN', 'https://olympics.com/en/athletes/rachel-homan'), ('John MORRIS', 'https://olympics.com/en/athletes/john-morris')]",False,5,Canada,CAN,...,NaN,NaN,,Nan,Rachel,HOMAN,https://olympics.com/en/athletes/rachel-homan,John,MORRIS,https://olympics.com/en/athletes/john-morris

In [12]:
def format_last_name(last_name):
    if last_name is None:
        return None
    # Split the last name by hyphen or space if present
    parts = [part.capitalize() for part in last_name.split('-' if '-' in last_name else ' ')]
    # Join the parts to form the formatted last name
    return '-'.join(parts) if '-' in last_name else ' '.join(parts)

# Apply the formatting function to 'athlete1_last_name' and 'athlete2_last_name' columns
results_data['athlete1_last_name'] = results_data['athlete1_last_name'].apply(format_last_name)
results_data['athlete2_last_name'] = results_data['athlete2_last_name'].apply(format_last_name)

results_data.head()

,discipline_title,event_title,slug_game,participant_type,medal_type,athletes,rank_equal,rank_position,country_name,country_3_letter_code,...,value_unit,value_type,first_name,last_name,athlete1_first_name,athlete1_last_name,athlete1_url,athlete2_first_name,athlete2_last_name,athlete2_url
0,Curling,Mixed Doubles,beijing-2022,GameTeam,GOLD,"[('Stefania CONSTANTINI', 'https://olympics.com/en/athletes/stefania-constantini'), ('Amos MOSANER', 'https://olympics.com/en/athletes/amos-mosaner')]",False,1,Italy,ITA,...,NaN,NaN,,Nan,Stefania,Constantini,https://olympics.com/en/athletes/stefania-constantini,Amos,Mosaner,https://olympics.com/en/athletes/amos-mosaner
1,Curling,Mixed Doubles,beijing-2022,GameTeam,SILVER,"[('Kristin SKASLIEN', 'https://olympics.com/en/athletes/kristin-skaslien'), ('Magnus NEDREGOTTEN', 'https://olympics.com/en/athletes/magnus-nedregotten')]",False,2,Norway,NOR,...,NaN,NaN,,Nan,Kristin,Skaslien,https://olympics.com/en/athletes/kristin-skaslien,Magnus,Nedregotten,https://olympics.com/en/athletes/magnus-nedregotten
2,Curling,Mixed Doubles,beijing-2022,GameTeam,BRONZE,"[('Almida DE VAL', 'https://olympics.com/en/athletes/almida-de-val'), ('Oskar ERIKSSON', 'https://olympics.com/en/athletes/oskar-eriksson')]",False,3,Sweden,SWE,...,NaN,NaN,,Nan,Almida,De Val,https://olympics.com/en/athletes/almida-de-val,Oskar,Eriksson,https://olympics.com/en/athletes/oskar-eriksson
3,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,"[('Jennifer DODDS', 'https://olympics.com/en/athletes/jennifer-dodds'), ('Bruce MOUAT', 'https://olympics.com/en/athletes/bruce-mouat')]",False,4,Great Britain,GBR,...,NaN,NaN,,Nan,Jennifer,Dodds,https://olympics.com/en/athletes/jennifer-dodds,Bruce,Mouat,https://olympics.com/en/athletes/bruce-mouat
4,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,"[('Rachel HOMAN', 'https://olympics.com/en/athletes/rachel-homan'), ('John MORRIS', 'https://olympics.com/en/athletes/john-morris')]",False,5,Canada,CAN,...,NaN,NaN,,Nan,Rachel,Homan,https://olympics.com/en/athletes/rachel-homan,John,Morris,https://olympics.com/en/athletes/john-morris

In [13]:
results_data.drop(['athletes', 'athlete_full_name'], axis=1, inplace=True)
results_data.head()

,discipline_title,event_title,slug_game,participant_type,medal_type,rank_equal,rank_position,country_name,country_3_letter_code,athlete_url,value_unit,value_type,first_name,last_name,athlete1_first_name,athlete1_last_name,athlete1_url,athlete2_first_name,athlete2_last_name,athlete2_url
0,Curling,Mixed Doubles,beijing-2022,GameTeam,GOLD,False,1,Italy,ITA,NaN,NaN,NaN,,Nan,Stefania,Constantini,https://olympics.com/en/athletes/stefania-constantini,Amos,Mosaner,https://olympics.com/en/athletes/amos-mosaner
1,Curling,Mixed Doubles,beijing-2022,GameTeam,SILVER,False,2,Norway,NOR,NaN,NaN,NaN,,Nan,Kristin,Skaslien,https://olympics.com/en/athletes/kristin-skaslien,Magnus,Nedregotten,https://olympics.com/en/athletes/magnus-nedregotten
2,Curling,Mixed Doubles,beijing-2022,GameTeam,BRONZE,False,3,Sweden,SWE,NaN,NaN,NaN,,Nan,Almida,De Val,https://olympics.com/en/athletes/almida-de-val,Oskar,Eriksson,https://olympics.com/en/athletes/oskar-eriksson
3,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,False,4,Great Britain,GBR,NaN,NaN,NaN,,Nan,Jennifer,Dodds,https://olympics.com/en/athletes/jennifer-dodds,Bruce,Mouat,https://olympics.com/en/athletes/bruce-mouat
4,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,False,5,Canada,CAN,NaN,NaN,NaN,,Nan,Rachel,Homan,https://olympics.com/en/athletes/rachel-homan,John,Morris,https://olympics.com/en/athletes/john-morris

In [14]:
results_data.head(50)

,discipline_title,event_title,slug_game,participant_type,medal_type,rank_equal,rank_position,country_name,country_3_letter_code,athlete_url,value_unit,value_type,first_name,last_name,athlete1_first_name,athlete1_last_name,athlete1_url,athlete2_first_name,athlete2_last_name,athlete2_url
0,Curling,Mixed Doubles,beijing-2022,GameTeam,GOLD,False,1,Italy,ITA,NaN,NaN,NaN,,Nan,Stefania,Constantini,https://olympics.com/en/athletes/stefania-constantini,Amos,Mosaner,https://olympics.com/en/athletes/amos-mosaner
1,Curling,Mixed Doubles,beijing-2022,GameTeam,SILVER,False,2,Norway,NOR,NaN,NaN,NaN,,Nan,Kristin,Skaslien,https://olympics.com/en/athletes/kristin-skaslien,Magnus,Nedregotten,https://olympics.com/en/athletes/magnus-nedregotten
2,Curling,Mixed Doubles,beijing-2022,GameTeam,BRONZE,False,3,Sweden,SWE,NaN,NaN,NaN,,Nan,Almida,De Val,https://olympics.com/en/athletes/almida-de-val,Oskar,Eriksson,https://olympics.com/en/athletes/oskar-eriksson
3,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,False,4,Great Britain,GBR,NaN,NaN,NaN,,Nan,Jennifer,Dodds,https://olympics.com/en/athletes/jennifer-dodds,Bruce,Mouat,https://olympics.com/en/athletes/bruce-mouat
4,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,False,5,Canada,CAN,NaN,NaN,NaN,,Nan,Rachel,Homan,https://olympics.com/en/athletes/rachel-homan,John,Morris,https://olympics.com/en/athletes/john-morris
5,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,False,6,Czech Republic,CZE,NaN,NaN,NaN,,Nan,Zuzana,Hajkova,https://olympics.com/en/athletes/zuzana-hajkova-1,Tomas,Paul,https://olympics.com/en/athletes/tomas-paul
6,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,False,7,Switzerland,SUI,NaN,NaN,NaN,,Nan,Jenny,Perret,https://olympics.com/en/athletes/perret,Martin,Rios,https://olympics.com/en/athletes/rios
7,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,False,8,United States of America,USA,NaN,NaN,NaN,,Nan,Vicky,Persinger,https://olympics.com/en/athletes/vicky-persinger,Christopher,Plys,https://olympics.com/en/athletes/christopher-plys
8,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,False,9,People's Republic of China,CHN,NaN,NaN,NaN,,Nan,Suyuan,Fan,https://olympics.com/en/athletes/suyuan-fan,Zhi,Ling,https://olympics.com/en/athletes/zhi-ling
9,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,False,10,Australia,AUS,NaN,NaN,NaN,,Nan,Tahli,Gill,https://olympics.com/en/athletes/tahli-gill,Dean,Hewitt,https://olympics.com/en/athletes/dean-hewitt
10,Curling,Women,beijing-2022,GameTeam,GOLD,False,1,Great Britain,GBR,NaN,NaN,NaN,,Nan,None,None,None,None,None,None
11,Curling,Women,beijing-2022,GameTeam,SILVER,False,2,Japan,JPN,NaN,NaN,NaN,,Nan,None,None,None,None,None,None
12,Curling,Women,beijing-2022,GameTeam,BRONZE,False,3,Sweden,SWE,NaN,NaN,NaN,,Nan,None,None,None,None,None,None
13,Curling,Women,beijing-2022,GameTeam,NaN,False,4,Switzerland,SUI,NaN,NaN,NaN,,Nan,None,None,None,None,None,None
14,Curling,Women,beijing-2022,GameTeam,NaN,False,5,Canada,CAN,NaN,NaN,NaN,,Nan,None,None,None,None,None,None
15,Curling,Women,beijing-2022,GameTeam,NaN,False,6,United States of America,USA,NaN,NaN,NaN,,Nan,None,None,None,None,None,None
16,Curling,Women,beijing-2022,GameTeam,NaN,False,7,People's Republic of China,CHN,NaN,NaN,NaN,,Nan,None,None,None,None,None,None
17,Curling,Women,beijing-2022,GameTeam,NaN,False,8,Republic of Korea,KOR,NaN,NaN,NaN,,Nan,None,None,None,None,None,None
18,Curling,Women,beijing-2022,GameTeam,NaN,False,9,Denmark,DEN,NaN,NaN,NaN,,Nan,None,None,None,None,None,None
19,Curling,Women,beijing-2022,GameTeam,NaN,False,10,ROC,ROC,NaN,NaN,NaN,,Nan,None,None,None,None,None,None
20,Curling,Men,beijing-2022,GameTeam,GOLD,False,1,Sweden,SWE,NaN,NaN,NaN,,Nan,None,None,None,None,None,None
21,Curling,Men,beijing-2022,GameTeam,SILVER,False,2,Great Britain,GBR,NaN,NaN,NaN,,Nan,None,None,None,None,None,None
22,Curling,Men,beijing-2022,GameTeam,BRONZE,False,3,Canada,CAN,NaN,NaN,NaN,,Nan,None,None,None,None,None,None
23,Curling,Men,beijing-2022,GameTeam,NaN,False,4,United States of America,USA,NaN,NaN,NaN,,Nan,None,None,None,None,None,None
24,Curling,Men,beijing-2022,GameTeam,NaN,False,5,People's Republic of China,CHN,NaN,NaN,NaN,,Nan,None,None,None,None,None,None
25,Curling,Men,beijing-2022,GameTeam,NaN,False,6,Norway,NOR,NaN,NaN,NaN,,Nan,None,None,None,None,None,None
26,Curling,Men,beijing-2022,GameTeam,NaN,False,7,Switzerland,SUI,NaN,NaN,NaN,,Nan,None,None,None,None,None,None
27,Curling,Men,beijing-2022,GameTeam,NaN,False,8,ROC,ROC,NaN,NaN,NaN,,Nan,None,None,None,None,None,None
28,Curling,Men,beijing-2022,GameTeam,NaN,False,9,Italy,ITA,NaN,NaN,NaN,,Nan,None,None,None,None,None,None
29,Curling,Men,beijing-2022,GameTeam,NaN,False,10,Denmark,DEN,NaN,NaN,NaN,,Nan,None,None,None,None,None,None
30,Freestyle Skiing,Men's Moguls,beijing-2022,Athlete,NaN,False,6,Australia,AUS,https://olympics.com/en/athletes/cooper-woods-topalovic,76.74,POINTS,Cooper,Woods-topalovic,None,None,None,None,None,None
31,Freestyle Skiing,Men's Moguls,beijing-2022,Athlete,NaN,False,17,Sweden,SWE,https://olympics.com/en/athletes/elofsson,78.87,POINTS,Felix,Elofsson,None,None,None,None,None,None
32,Freestyle Skiing,Men's Moguls,beijing-2022,Athlete,NaN,False,16,United States of America,USA,https://olympics.com/en/athletes/dylan-walczyk,75.86,POINTS,Dylan,Walczyk,None,None,None,None,None,None
33,Freestyle Skiing,Men's Moguls,beijing-2022,Athlete,NaN,False,19,Finland,FIN,https://olympics.com/en/athletes/olli-penttala,75.95,POINTS,Olli,Penttala,None,None,None,None,None,None
34,Freestyle Skiing,Men's Moguls,beijing-2022,Athlete,NaN,False,8,Kazakhstan,KAZ,https://olympics.com/en/athletes/reikherd,75.43,POINTS,Dmitriy,Reikherd,None,None,None,None,None,None
35,Freestyle Skiing,Men's Moguls,beijing-2022,Athlete,NaN,False,29,Australia,AUS,https://olympics.com/en/athletes/matt-graham,65.13,POINTS,Matt,Graham,None,None,None,None,None,None
36,Freestyle Skiing,Men's Moguls,beijing-2022,Athlete,BRONZE,False,3,Japan,JPN,https://olympics.com/en/athletes/ikuma-horishima,76.19,POINTS,Ikuma,Horishima,None,None,None,None,None,None
37,Freestyle Skiing,Men's Moguls,beijing-2022,Athlete,NaN,False,7,Japan,JPN,https://olympics.com/en/athletes/daichi-hara,76.11,POINTS,Daichi,Hara,None,None,None,None,None,None
38,Freestyle Skiing,Men's Moguls,beijing-2022,Athlete,NaN,False,26,Canada,CAN,https://olympics.com/en/athletes/laurent-dumais,71.39,POINTS,Laurent,Dumais,None,None,None,None,None,None
39,Freestyle Skiing,Men's Moguls,beijing-2022,Athlete,NaN,False,24,Australia,AUS,https://olympics.com/en/athletes/james-matheson,73.20,POINTS,James,Matheson,None,None,None,None,None,None
40,Freestyle Skiing,Men's Moguls,beijing-2022,Athlete,NaN,False,21,Kazakhstan,KAZ,https://olympics.com/en/athletes/pavel-kolmakov,74.09,POINTS,Pavel,Kolmakov,None,None,None,None,None,None
41,Freestyle Skiing,Men's Moguls,beijing-2022,Athlete,NaN,False,9,Japan,JPN,https://olympics.com/en/athletes/kosuke-sugimoto,76.26,POINTS,Kosuke,Sugimoto,None,None,None,None,None,None
42,Freestyle Skiing,Men's Moguls,beijing-2022,Athlete,NaN,False,10,Australia,AUS,https://olympics.com/en/athletes/brodie-summers,77.93,POINTS,Brodie,Summers,None,None,None,None,None,None
43,Freestyle Skiing,Men's Moguls,beijing-2022,Athlete,NaN,False,28,Finland,FIN,https://olympics.com/en/athletes/severi-vierela,69.16,POINTS,Severi,Vierela,None,None,None,None,None,None
44,Freestyle Skiing,Men's Moguls,beijing-2022,Athlete,NaN,False,18,Switzerland,SUI,https://olympics.com/en/athletes/marco-tade,74.48,POINTS,Marco,Tade,None,None,None,None,None,None
45,Freestyle Skiing,Men's Moguls,beijing-2022,Athlete,NaN,False,27,Great Britain,GBR,https://olympics.com/en/athletes/william-feneley,70.23,POINTS,William,Feneley,None,None,None,None,None,None
46,Freestyle Skiing,Men's Moguls,beijing-2022,Athlete,SILVER,False,2,Canada,CAN,https://olympics.com/en/athletes/mikael-kingsbury,81.15,POINTS,Mikael,Kingsbury,None,None,None,None,None,None
47,Freestyle Skiing,Men's Moguls,beijing-2022,Athlete,NaN,False,23,Japan,JPN,https://olympics.com/en/athletes/so-matsuda,73.35,POINTS,So,Matsuda,None,None,None,None,None,None
48,Freestyle Skiing,Men's Moguls,beijing-2022,Athlete,GOLD,False,1,Sweden,SWE,https://olympics.com/en/athletes/wallberg,79.12,POINTS,Walter,Wallberg,None,None,None,None,None,None
49,Freestyle Skiing,Men's Moguls,beijing-2022,Athlete,NaN,False,25,United States of America,USA,https://olympics.com/en/athletes/bradley-wilson,72.94,POINTS,Bradley,Wilson,None,None,None,None,None,None

In [15]:
results_data.columns

Index(['discipline_title', 'event_title', 'slug_game', 'participant_type',
       'medal_type', 'rank_equal', 'rank_position', 'country_name',
       'country_3_letter_code', 'athlete_url', 'value_unit', 'value_type',
       'first_name', 'last_name', 'athlete1_first_name', 'athlete1_last_name',
       'athlete1_url', 'athlete2_first_name', 'athlete2_last_name',
       'athlete2_url'],
      dtype='object')

In [25]:

# Filter the DataFrame based on participant_type
game_team_data = results_data[results_data['participant_type'] == 'GameTeam']

# Selecting columns related to athlete 1 and athlete 2
athlete_columns = ['athlete1_first_name', 'athlete1_last_name', 'athlete1_url',
                   'athlete2_first_name', 'athlete2_last_name', 'athlete2_url']

# Creating a new DataFrame with only the selected columns for GameTeam participants
game_team_athletes_data = game_team_data[athlete_columns].copy()

# Displaying the first few rows of the new DataFrame
game_team_athletes_data.head(50)

,athlete1_first_name,athlete1_last_name,athlete1_url,athlete2_first_name,athlete2_last_name,athlete2_url
0,Stefania,Constantini,https://olympics.com/en/athletes/stefania-constantini,Amos,Mosaner,https://olympics.com/en/athletes/amos-mosaner
1,Kristin,Skaslien,https://olympics.com/en/athletes/kristin-skaslien,Magnus,Nedregotten,https://olympics.com/en/athletes/magnus-nedregotten
2,Almida,De Val,https://olympics.com/en/athletes/almida-de-val,Oskar,Eriksson,https://olympics.com/en/athletes/oskar-eriksson
3,Jennifer,Dodds,https://olympics.com/en/athletes/jennifer-dodds,Bruce,Mouat,https://olympics.com/en/athletes/bruce-mouat
4,Rachel,Homan,https://olympics.com/en/athletes/rachel-homan,John,Morris,https://olympics.com/en/athletes/john-morris
5,Zuzana,Hajkova,https://olympics.com/en/athletes/zuzana-hajkova-1,Tomas,Paul,https://olympics.com/en/athletes/tomas-paul
6,Jenny,Perret,https://olympics.com/en/athletes/perret,Martin,Rios,https://olympics.com/en/athletes/rios
7,Vicky,Persinger,https://olympics.com/en/athletes/vicky-persinger,Christopher,Plys,https://olympics.com/en/athletes/christopher-plys
8,Suyuan,Fan,https://olympics.com/en/athletes/suyuan-fan,Zhi,Ling,https://olympics.com/en/athletes/zhi-ling
9,Tahli,Gill,https://olympics.com/en/athletes/tahli-gill,Dean,Hewitt,https://olympics.com/en/athletes/dean-hewitt
10,None,None,None,None,None,None
11,None,None,None,None,None,None
12,None,None,None,None,None,None
13,None,None,None,None,None,None
14,None,None,None,None,None,None
15,None,None,None,None,None,None
16,None,None,None,None,None,None
17,None,None,None,None,None,None
18,None,None,None,None,None,None
19,None,None,None,None,None,None
20,None,None,None,None,None,None
21,None,None,None,None,None,None
22,None,None,None,None,None,None
23,None,None,None,None,None,None
24,None,None,None,None,None,None
25,None,None,None,None,None,None
26,None,None,None,None,None,None
27,None,None,None,None,None,None
28,None,None,None,None,None,None
29,None,None,None,None,None,None
202,None,None,None,None,None,None
203,None,None,None,None,None,None
204,None,None,None,None,None,None
205,None,None,None,None,None,None
206,None,None,None,None,None,None
207,None,None,None,None,None,None
425,None,None,None,None,None,None
426,None,None,None,None,None,None
427,None,None,None,None,None,None
428,None,None,None,None,None,None
429,None,None,None,None,None,None
430,None,None,None,None,None,None
431,None,None,None,None,None,None
432,None,None,None,None,None,None
433,None,None,None,None,None,None
434,None,None,None,None,None,None
435,None,None,None,None,None,None
436,None,None,None,None,None,None
437,None,None,None,None,None,None
438,None,None,None,None,None,None

In [21]:
import pandas as pd

# Assuming your original DataFrame is named results_data

# Filter the DataFrame based on participant_type
athlete_data = results_data[results_data['participant_type'] == 'Athlete']

# Separate first_name and last_name
first_name = athlete_data['first_name'].copy()
last_name = athlete_data['last_name'].copy()

# For rows where last_name is NaN, fill it with an empty string
last_name.fillna('', inplace=True)

# Create a new DataFrame with separated first_name and last_name
athlete_names = pd.DataFrame({
    'first_name': first_name,
    'last_name': last_name
})

# Displaying the first few rows of the new DataFrame
athlete_names.head()

   first_name        last_name
30     Cooper  Woods-topalovic
31      Felix         Elofsson
32      Dylan          Walczyk
33       Olli         Penttala
34    Dmitriy         Reikherd

In [24]:

# Reset indices of both DataFrames
athlete_names.reset_index(drop=True, inplace=True)
game_team_athletes_data.reset_index(drop=True, inplace=True)

# Concatenate the DataFrames along the columns axis
combined_data = pd.concat([athlete_names, game_team_athletes_data], axis=1)

# Display the combined DataFrame
combined_data.head(50)

,first_name,last_name,athlete1_first_name,athlete1_last_name,athlete1_url,athlete2_first_name,athlete2_last_name,athlete2_url
0,Cooper,Woods-topalovic,Stefania,Constantini,https://olympics.com/en/athletes/stefania-constantini,Amos,Mosaner,https://olympics.com/en/athletes/amos-mosaner
1,Felix,Elofsson,Kristin,Skaslien,https://olympics.com/en/athletes/kristin-skaslien,Magnus,Nedregotten,https://olympics.com/en/athletes/magnus-nedregotten
2,Dylan,Walczyk,Almida,De Val,https://olympics.com/en/athletes/almida-de-val,Oskar,Eriksson,https://olympics.com/en/athletes/oskar-eriksson
3,Olli,Penttala,Jennifer,Dodds,https://olympics.com/en/athletes/jennifer-dodds,Bruce,Mouat,https://olympics.com/en/athletes/bruce-mouat
4,Dmitriy,Reikherd,Rachel,Homan,https://olympics.com/en/athletes/rachel-homan,John,Morris,https://olympics.com/en/athletes/john-morris
5,Matt,Graham,Zuzana,Hajkova,https://olympics.com/en/athletes/zuzana-hajkova-1,Tomas,Paul,https://olympics.com/en/athletes/tomas-paul
6,Ikuma,Horishima,Jenny,Perret,https://olympics.com/en/athletes/perret,Martin,Rios,https://olympics.com/en/athletes/rios
7,Daichi,Hara,Vicky,Persinger,https://olympics.com/en/athletes/vicky-persinger,Christopher,Plys,https://olympics.com/en/athletes/christopher-plys
8,Laurent,Dumais,Suyuan,Fan,https://olympics.com/en/athletes/suyuan-fan,Zhi,Ling,https://olympics.com/en/athletes/zhi-ling
9,James,Matheson,Tahli,Gill,https://olympics.com/en/athletes/tahli-gill,Dean,Hewitt,https://olympics.com/en/athletes/dean-hewitt
10,Pavel,Kolmakov,None,None,None,None,None,None
11,Kosuke,Sugimoto,None,None,None,None,None,None
12,Brodie,Summers,None,None,None,None,None,None
13,Severi,Vierela,None,None,None,None,None,None
14,Marco,Tade,None,None,None,None,None,None
15,William,Feneley,None,None,None,None,None,None
16,Mikael,Kingsbury,None,None,None,None,None,None
17,So,Matsuda,None,None,None,None,None,None
18,Walter,Wallberg,None,None,None,None,None,None
19,Bradley,Wilson,None,None,None,None,None,None
20,Yang,Zhao,None,None,None,None,None,None
21,Benjamin,Cavet,None,None,None,None,None,None
22,Cole,Mcdonald,None,None,None,None,None,None
23,Nick,Page,None,None,None,None,None,None
24,Sacha,Theocharis,None,None,None,None,None,None
25,Jimi,Salonen,None,None,None,None,None,None
26,Nikita,Novitskii,None,None,None,None,None,None
27,Nikita,Andreev,None,None,None,None,None,None
28,Ludvig,Fjallstrom,None,None,None,None,None,None
29,Oskar,Elofsson,None,None,None,None,None,None
30,Bingqiang,Mao,None,None,None,None,None,None
31,Kevin,Rolland,None,None,None,None,None,None
32,Noah,Bowman,None,None,None,None,None,None
33,Robin,Briguet,None,None,None,None,None,None
34,Nico,Porteous,None,None,None,None,None,None
35,Seung,Hun Lee,None,None,None,None,None,None
36,David,Wise,None,None,None,None,None,None
37,Aaron,Blunck,None,None,None,None,None,None
38,Brendan,Mackay,None,None,None,None,None,None
39,Ben,Harrington,None,None,None,None,None,None
40,Jingbo,Sun,None,None,None,None,None,None
41,Alex,Ferreira,None,None,None,None,None,None
42,Miguel,Porteous,None,None,None,None,None,None
43,Brendan,Newby,None,None,None,None,None,None
44,Gus,Kenworthy,None,None,None,None,None,None
45,Gustav,Legnavsky,None,None,None,None,None,None
46,Haizhuo,Wang,None,None,None,None,None,None
47,Marco,Ladner,None,None,None,None,None,None
48,Binghan,He,None,None,None,None,None,None
49,Birk,Irving,None,None,None,None,None,None